import os

# ********************************************************************************************************************************
# To be updated by user accordingly if to run this script using saved csv files
# Replace 'example_xxx.csv' with user's file name
xFeature_filename = 'features_housing.csv'
yTrue_filename = 'yTrue.csv'
yPred_filename = ['yPreds_lasso.csv', 'yPreds_rf.csv']  # can be single file or max 2 files, wrap in a list

# model name must be listed according to the same sequence of the yPred_filename list above in order to 
# indicate the prediction outputs are generated by the mentioned model
MODEL_NAME_LIST = ['lasso', 'random_forest']  # can be single model or max bi-modal, wrap in a list
ANALYSIS_TYPE = 'Regression'  # Supported analysis types : 'Regression', 'Binary Classification', 'Multiclass Classification'
ANALYSIS_TITLE = 'Housing Price Prediction'
# *******************************************************************************************************************************

# No modification from user is needed from this line onwards
DATA_DIR = 'csv_data'
XFEATURE_FILEPATH = os.path.join(DATA_DIR, xFeature_filename)
YTRUE_FILEPATH = os.path.join(DATA_DIR, yTrue_filename)
YPRED_FILEPATH = [os.path.join(DATA_DIR, file) for file in yPred_filename]
